install.packages("tidyverse")
install.packages("bookdown")
install.packages("httr")
install.packages('leaflet')
install.packages('caTools')
installed.packages('rprojroot')
devtools::install_github("liao961120/pttR")
