#!/bin/bash

# Beakerx installation and extension
beakerx install
jupyter labextension install beakerx-jupyterlab
jupyter labextension install @jupyter-widgets/jupyterlab-manager

# Git Jupyter Lab extension
jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git

# Github Jupyter Lab extension
jupyter labextension install @jupyterlab/github

# Draw.io Jupyter Lab extension
jupyter labextension install jupyterlab-drawio

# Rise Jupyter extension (presentation mode)
jupyter-nbextension install rise --py --sys-prefix
jupyter-nbextension enable  rise --py --sys-prefix
jupyter labextension install jupyterlab_rise

# Plotly Jupyter Lab extension
jupyter labextension install @jupyterlab/plotly-extension

# Table of contents Jupyter Lab Extension
jupyter labextension install @jupyterlab/toc

# Latex Jupyter Lab extension
jupyter labextension install @jupyterlab/latex

# SPARQL kernel
jupyter sparqlkernel install --user

# Building everything
jupyter lab build

# final touches
rm conda-bld -R

# tema
jt -t grade3 -fs 12 -tfs 125 -nfs 115 -ofs 11 -dfs 11 -cellw 78% -T -kl -altp -altmd -altout
