install.packages("ggplot2")
install.packages("tidyr")
install.packages("dplyr")
install.packages("vegan")
install.packages("pheatmap")
source("https://bioconductor.org/biocLite.R")
BiocInstaller::biocLite(c("GenomicAlignments", "VariantAnnotation", "Biostrings", "GenomicFeatures"))
