#!/bin/bash
# a word
#
# build CoolProp for Julia
julia -e 'if (VERSION > v"0.7-") using Pkg; else Pkg.init(); end; Pkg.clone("https://github.com/vimalaad/CoolProp.jl.git"); Pkg.build("CoolProp")'

# Disable deprecated warnings in Julia 0.6
julia -e 'if (VERSION < v"0.7-") using IJulia; IJulia.installkernel("Julia nodeps", "--depwarn=no"); end;'


#setenv("JULIA_VERSION", "1.0.2")
#
# JULIA_VERSION="1.0.2"
# # # setenv("JULIA_VERSION", "1.0.2")
# mkdir -p ${JULIA_PATH} && curl -sSL "https://julialang-s3.julialang.org/bin/linux/x64/${JULIA_VERSION%[.-]*}/julia-${JULIA_VERSION}-linux-x86_64.tar.gz" | tar -xz -C ${JULIA_PATH} --strip-components 1
# julia -e 'if (VERSION > v"0.7-") using Pkg; else Pkg.init(); end; Pkg.add("IJulia"); using IJulia;' && mv ${HOME}/.local/share/jupyter/kernels/julia-${JULIA_VERSION%[.-]*}  ${NB_PYTHON_PREFIX}/share/jupyter/kernels/julia-${JULIA_VERSION%[.-]*}
