install.packages("twitteR")
install.packages("ROAuth")
install.packages("RCurl")
install.packages("tm")
install.packages("httr")
install.packages("curl")
install.packages("SnowballC")
install.packages("wordcloud")
install.packages("reshape")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("tidytext")
install.packages("topicmodels")
install.packages("ldatuning")


