install.packages(c("here", "remotes"))
remotes::install_github("hadley/ggplot2")
remotes::install_github("hadley/emo")
remotes::install_github("r-quantities/units")
remotes::install_github("uribo/jpmesh")
