install.packages('rgdal')
install.packages("raster")
install.packages("devtools")
install.packages("reshape2")
install.packages("dplyr")
install.packages("sp")
install.packages("prism")
install.packages('dataRetrieval')