install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("caret")
install.packages("e1071")
install.packages("keras")
install.packages("mlbench")
install.packages("ggthemes")
install.packages("assertthat")
install.packages("kernlab")
install.packages("rpart")
install.packages("rattle")
install.packages("kknn")
install.packages("randomForest")
install.packages('nnet')
install.packages('RSNNS')
install.packages('Metrics')
install.packages('AUC')
install.packages('plotly')
install.packages('rBayesianOptimization')

tensorflow::install_tensorflow()
keras::install_keras()

tmp <- keras::dataset_mnist()
