install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("ggplot2")
install.packages("data.table")
install.packages("lattice")
install.packages("caret")
install.packages('e1071')
install.packages('R.utils')
