#!/bin/bash

#jupyter contrib nbextension install --user

#enable githubcommit extension for all notebooks

git clone https://github.com/sat28/githubcommit.git

source ~/env.sh

jupyter serverextension enable --py githubcommit
jupyter nbextension install --py githubcommit
jupyter nbextension enable --py githubcommit

jupyter serverextension enable --py nbdime
jupyter nbextension install --py nbdime
jupyter nbextension enable --py nbdime



