install.packages("inline", dependencies = c("Depends", "Imports", "LinkingTo"))
install.packages("ggplot2", dependencies = c("Depends", "Imports", "LinkingTo"))
install.packages("gridExtra", dependencies = c("Depends", "Imports", "LinkingTo"))
install.packages("Rcpp", dependencies = c("Depends", "Imports", "LinkingTo"))
install.packages("RcppEigen", dependencies = c("Depends", "Imports", "LinkingTo"))
install.packages("BH", dependencies = c("Depends", "Imports", "LinkingTo"))
install.packages("StanHeaders", dependencies = c("Depends", "Imports", "LinkingTo"))
install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages("tidyverse", repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages("rstanarm", repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages("bayesplot", dependencies = c("Depends", "Imports", "LinkingTo"))
