install.packages("tidyverse", dep=TRUE)
install.packages("dplyr", dep=TRUE)
install.packages("devtools", dep=TRUE)
install.packages("ggplot2", dep=TRUE)
install.packages("sf", dep=TRUE)
install.packages("rstan")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
